### ISSUE TITLE
USER STORY: VIEWING: View specific product

### ISSUE THREAD

**Issue by arthurmezaonik** [arthurmezaonik/portfolio_project_05#10]
# DESCRIPTION
As a **user** I can **view a specific product ** so that **I can identify the price, description and read the reviews**

# ACCEPTANCE CRITERIA
1. Be able to see the price
2. Be able to see the description
3. Be able to see reviews

# TASKS
- [ ] Create the specific product view
- [ ] Create the specific product template
- [ ] Create the specific product url
- [ ] Display the product's reviews
