### ISSUE TITLE
USER STORY: VIEWING: View specific blog post

### ISSUE THREAD

**Issue by arthurmezaonik** [arthurmezaonik/portfolio_project_05#11]
# DESCRIPTION
As a **user** I can **view a specific blog post** so that **I can read the full content**

# ACCEPTANCE CRITERIA
1. Be able to read the blog post

# TASKS
- [ ] Create specific blog post view
- [ ] Create specific blog post template
- [ ] Create specific blog post url
