### ISSUE TITLE
USER STORY: SORT & SEARCH: Search

### ISSUE THREAD

**Issue by arthurmezaonik** [arthurmezaonik/portfolio_project_05#15]
# DESCRIPTION
As a **user** I can **search for specific keywords** so that **I can find specific products and blogs based on a specific keyword**

# ACCEPTANCE CRITERIA
1. Be able to sort for a specific keyword
2. Be able to see a list with the results

# TASKS
- [ ] Add a search form
- [ ] Create a specific view to handle the search function
- [ ] Create a search template to display the results
- [ ] Create a search url
