### ISSUE TITLE
USER STORY: CHECKOUT: Payment

### ISSUE THREAD

**Issue by arthurmezaonik** [arthurmezaonik/portfolio_project_05#16]
# DESCRIPTION
As a **user** I can **make a card payment** so that **I can finalize my purchase**

# ACCEPTANCE CRITERIA
1. Be able to make a payment

# TASKS
- [ ] Set up Stripe
- [ ] Create checkout view
- [ ] Create checkout template
- [ ] Create checkout url
- [ ] Create checkout functions
