### ISSUE TITLE
USER STORY: VIEWING: List Of Products

### ISSUE THREAD

**Issue by arthurmezaonik** [arthurmezaonik/portfolio_project_05#8]
# DESCRIPTION
As a **user** I can **see all the products on a page** so that **I can decide what product I want to check**

# ACCEPTANCE CRITERIA
1. Be able to see all the products on the page
2. Be able to sort the products
3. Be able to filter the products

# TASKS
- [ ] Create the products list view
- [ ] Create the products list template
- [ ] Create the products list urls
- [ ] Add the functions to sort and filter the products
